### ISSUE TITLE
hs2 extractor wrong propert handling

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikeextractors#101]
@colehurwitz31 @mhhennig 

This https://github.com/SpikeInterface/spikeextractors/blob/master/spikeextractors/extractors/hs2sortingextractor/hs2sortingextractor.py#L42-L48 is wrong as it only allows `spike_locations` and `unit_location` to be property. 

Can you fix that? you should set the property instead.

**Comment by colehurwitz31** [comment]
I will fix this today.

**Comment by colehurwitz31** [comment]
Fixed and merged!
