### ISSUE TITLE
Removal of UnitSpikeFeatures

### ISSUE THREAD

**Issue by colehurwitz31** [SpikeInterface/spikeextractors#106]
I was considering removing UnitSpikeFeatures (set, get, etc.) from the SortingExtractor. Is anyone using this method extensively? 

We can already store arrays of values with the UnitProperty functions so I don't know if the UnitSpikeFeatures methods are necessary. Also, it is a bit annoying to keep track of multiple dictionaries. What are your guys thoughts?

@alejoe91 @magland @samuelgarcia @mhhennig

**Comment by alejoe91** [comment]
Yes! I use it to load waveforms and PCA scores. Please keep it ;)

Spike features is very different than property, as each feature is for a spike, the property is for the unit.

**Comment by colehurwitz31** [comment]
Ok, good to know :).
