### ISSUE TITLE
Store spike train counts as properties

### ISSUE THREAD

**Issue by colehurwitz** [SpikeInterface/spikeextractors#141]
I find myself extracting spike trains and getting there lengths all the times. Upon initialisation, do you think storing spike train counts automatically as a property and then giving an easy way to access them (get_unit_spiketrain_counts()) would be a good idea?

**Comment by mhhennig** [comment]
Could take a while to compute for large data, but should be useful:
```python
self._num_spikes_units = [len(self.get_unit_spike_train(i)) for i in self.get_unit_ids()]
```

**Comment by colehurwitz31** [comment]
I would store it in the properties dictionary, but I thought it would be useful as well

**Comment by colehurwitz31** [comment]
We could have a Boolean flag in the sorting extractor parent class that is false by default for loading spike train counts

**Comment by mhhennig** [comment]
Or create a function `get_unit_spiketrain_counts()` in the parent class that computes counts and adds them as property when first called? Could this potentially break anything?

**Comment by colehurwitz31** [comment]
No, it wouldn’t break anything, but it should probably be optional
