### ISSUE TITLE
MEArecRecordingExtractor and MEArecSortingExtractor are quite slow

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spikeextractors#142]
I am playing a bit with mearec theses days.
I found that MEArecRecordingExtractor and MEArecSortingExtractor are quite slow.
I don't have time to read the mearec code for IO but I think that **mr.load_recordings** load many thing in memory. there are no memmap or lazy loading.
Am I wrong ?

**Comment by alejoe91** [comment]
There should be a memmap of the h5 files for the recording extractor. I will check.
For the sorting extractor it probably loads the waveforms in memory..we could delete the object later

**Comment by samuelgarcia** [comment]
At the moment it is not a probleme of memory use but time to load everyhting.
I think you could put some load on demand for waveform (and everything).

If you had used the neo rawio API ...

**Comment by alejoe91** [comment]
Eheheh we can discuss about that! Indeed spiketrains are neo spike trains, so it should be easy to load them with the neo api

**Comment by samuelgarcia** [comment]
It is my secret plan : base spikeextractor on neo.rawio API with a simple wrapper.
But I don't think I will have before 2022. :)

**Comment by colehurwitz** [comment]
All done with this @alejoe91 ?

**Comment by alejoe91** [comment]
yep

**Comment by hoducha92** [comment]
Quá phức tạp dề nghị có tiếng 5nam

**Comment by colehurwitz** [comment]
Not too complicated! Just making sure our file IO is up to speed :) if you have any questions, let us know.

**Comment by hoducha92** [comment]
Đề nghị cho tiếng việt nam thì sẽ tiếp xúc nhiều người

**Comment by colehurwitz** [comment]
Unfortunately, none of us speak Vietnamese. However, if you would like to help us translate our [readthedocs](https://github.com/SpikeInterface/spikeinterface/tree/master/doc) into Vietnamese, you can make a pull request. Here is a link about how to do this: https://docs.readthedocs.io/en/stable/localization.html. Thanks for checkout out our project!
