### ISSUE TITLE
Hard dependencies in spikeextractors

### ISSUE THREAD

**Issue by colehurwitz** [SpikeInterface/spikeextractors#145]
Currently, we only have numpy as a hard dependency for spikeextractors which allows you to use a subset of extractors by default.

Do you think it might be good to include **h5py** as a hard dependency since that would enable many more extractors to be used immediately (klusta, hs2, biocam, spyking, etc.)?

Curious on your thoughts, @magland @samuelgarcia @alejoe91

**Comment by colehurwitz** [comment]
We can think about this post-release

**Comment by colehurwitz** [comment]
I still think this is potentially a good idea. Thoughts?

**Comment by samuelgarcia** [comment]
Personnaly I would prefer to keep H5 as a weak dependency.
H5 is sometimes a pain to install.
