### ISSUE TITLE
Should get_unit_ids return list or numpy array?

### ISSUE THREAD

**Issue by colehurwitz** [SpikeInterface/spikeextractors#164]
So depending on the SortingExtractor, some will return a list of unit ids and others will return a numpy array of unit ids.

Which would you prefer between the two? @samuelgarcia Pointed out that we should probably choose one, and I prefer the list being return each time. I can fix this if we agree.

@samuelgarcia @magland @alejoe91

**Comment by samuelgarcia** [comment]
A list is fine for me.

**Comment by alejoe91** [comment]
let's keep lists

**Comment by colehurwitz** [comment]
Ok, I can go update everything.
