### ISSUE TITLE
Spikeextractors README ok?

### ISSUE THREAD

**Issue by colehurwitz** [SpikeInterface/spikeextractors#168]
I feel as though the README might be a little verbose and not as clear (the example is quite long), what do you guys think? @alejoe91 @mhhennig @samuelgarcia 

I can shorten it and make it more clear if you guys think it is lacking.

**Comment by mhhennig** [comment]
I think it is good as all the info is there. Myabe move the colab link to the top?

**Comment by alejoe91** [comment]
The colab is totally broken though. It still imports spikeinterface as si...I would remove it from both READMEs

**Comment by samuelgarcia** [comment]
An the collab example was before 2 big refactoring:
 * sorter as class
 * comaprison

So yes, lets remove the link.
