### ISSUE TITLE
HS2 extractor is extremely slow

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikeextractors#180]
tested on the retina dataset, it takes 20 minutes to load a sorting extractor

**Comment by samuelgarcia** [comment]
And mearec extractor is "quite" slow :)

**Comment by samuelgarcia** [comment]
npz is quite fast :)

**Comment by alejoe91** [comment]
I think MEArec is quite slow because it loads waveforms..I'll make it optional

**Comment by samuelgarcia** [comment]
And it load signals also, no ?

**Comment by alejoe91** [comment]
no all memmapped

**Comment by colehurwitz** [comment]
Will work on this. Probably has to do with all the extra info we load in as properties. We could always make this optional if that is the problem.

**Comment by mhhennig** [comment]
I checked, it is `set_unit_spike_features` that's rather slow. I think it is all the checking it does. It should be possible to circumvent this function during creation, correct?

**Comment by mhhennig** [comment]
Just made a PR with some changes that speeds up the loading of extra info in HS2 files.

**Comment by alejoe91** [comment]
can we close this?

**Comment by colehurwitz** [comment]
Yep!
