### ISSUE TITLE
Why is the set_sampling_frequency not in the SortingExtractor?????

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikeextractors#202]

**Comment by colehurwitz** [comment]
I think that @samuelgarcia wanted the get_sampling_frequency to be a file specific function (kinda like get_traces), not some set and get function.

**Comment by colehurwitz** [comment]
Might be good to have though!

**Comment by alejoe91** [comment]
Ah ok! I need it for the spikesorters! making a PR

**Comment by samuelgarcia** [comment]
I am OK to have set_sampling_frequency.
I think I did not writte at the beginiing but we can.

**Comment by alejoe91** [comment]
Done :)
