### ISSUE TITLE
request: PlexonExtractor

### ISSUE THREAD

**Issue by bendichter** [SpikeInterface/spikeextractors#224]

**Comment by samuelgarcia** [comment]
This will be handle when I will implement the neo extractor layer.

**Comment by samuelgarcia** [comment]
Hi @bendichter.
Could you test the PR #291 ?
Plexon is implemented with a neo wrapper.
Cheers
Samuel

**Comment by samuelgarcia** [comment]
THere is a travis bug due to PyQT5.
Maybe we can force a version for this or wait a bit.

**Comment by alejoe91** [comment]
implemented
