### ISSUE TITLE
spike times as integers?

### ISSUE THREAD

**Issue by luiztauffer** [SpikeInterface/spikeextractors#226]
Any specific reason why spike times are returned as integers in `NumpySortingExtractor` [this line](https://github.com/SpikeInterface/spikeextractors/blob/1466e03802060b661071de2df70870046082112e/spikeextractors/extractors/numpyextractors/numpyextractors.py#L82) ?

**Comment by alejoe91** [comment]
@luiztauffer as spike train unit we use number of frames/samples in the entire spikeinterface framework. They can be quickly converted using the sampling frequency.

**Comment by luiztauffer** [comment]
@alejoe91 thanks!

**Comment by samuelgarcia** [comment]
By the way. spiektimes should be renames as spiekindexex. This would avoid confusion No ?
