### ISSUE TITLE
get_shared_unit_property_names() method for SortingExtractor

### ISSUE THREAD

**Issue by luiztauffer** [SpikeInterface/spikeextractors#244]
Suggestion:
The recent update on RecordingExtractor giving the method get_shared_channel_property_names() was very nice, how about doing a similar method for SortingExtractor, e.g. get_shared_unit_property_names() ?

**Comment by alejoe91** [comment]
I totally agree :) We should definitely do that. It might take a few dates as we have to update all packages.

**Comment by colehurwitz** [comment]
Good catch. I’ll do this today.

**Comment by colehurwitz** [comment]
#245 

I also updated spiketoolkit and spikewidgets to match this new functionality (all other repos did not use these functions).

**Comment by samuelgarcia** [comment]
You shoudl update spikeinterface/examples.
examples elsewhere should be removed.

**Comment by colehurwitz** [comment]
I updated the spikeinterface examples

**Comment by colehurwitz** [comment]
Should I remove all examples from the other repos? Just delete the examples folders?

**Comment by samuelgarcia** [comment]
@alejoe91 ?

**Comment by colehurwitz** [comment]
Alessio just told me to delete the folders. Will do
