### ISSUE TITLE
Suggestion: Tutorials directory

### ISSUE THREAD

**Issue by luiztauffer** [SpikeInterface/spikeextractors#249]
Hi, together with the NWB extractors extension I prepared a Jupyter notebook tutorial on how to use SpikeExtractors with NWB files.
I was wondering if you guys would like to have it somewhere, e.g. a tutorials directory.

**Comment by colehurwitz** [comment]
We have a [spiketutorials](https://github.com/SpikeInterface/spiketutorials) package that might be a good fit for this! We have one workshop tutorial for building general pipelines, but it would be nice to have a good tutorial about integration into NWB.

**Comment by samuelgarcia** [comment]
We also have tutorial (generated to notebook) here in spikeinterface meta package:

[source](https://github.com/SpikeInterface/spikeinterface/tree/master/examples)
and
[tutorial galery](https://spikeinterface.readthedocs.io/en/latest/modules/index.html)

**Comment by alejoe91** [comment]
I think it would be nice it to have it in the docs. @luiztauffer is the notebook on github?

**Comment by luiztauffer** [comment]
not yet, but I can PR it to the spiketutorials repo and you guys can decide if it's worth it to put on documentation or anywhere else 
:)

**Comment by alejoe91** [comment]
Sounds good! :)

**Comment by alejoe91** [comment]
@luiztauffer an update on this.

We have now a github.io page (https://github.com/SpikeInterface/SpikeInterface.github.io) that uses nikola and it allows to have several notebooksin the same place: https://spikeinterface.github.io/

Probably this would be a better place to have an SI-NWB tutorial
