### ISSUE TITLE
tkinter dependency ?

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spikeextractors#255]
In readSGLX we have a hard dependency on tkinter.
I think we should not hve this at all.
tkinter leads to many install problems in virtual env and extractor should have UI toolkit dep. No ?

**Comment by colehurwitz** [comment]
I agree. It may not even be used in the main code. I removed a matplotlib requirement which wasn’t being used.

**Comment by colehurwitz** [comment]
#256
