### ISSUE TITLE
BinaryDatRecordingExtractor 'frames_first'

### ISSUE THREAD

**Issue by colehurwitz** [SpikeInterface/spikeextractors#260]
Should the `frames_first` bool in the constructor be the same as the `time_axis` integer in the write_recording? 

https://github.com/SpikeInterface/spikeextractors/blob/master/spikeextractors/extractors/bindatrecordingextractor/bindatrecordingextractor.py

**Comment by alejoe91** [comment]
Yesss

**Comment by colehurwitz** [comment]
Can you fix this? I am not too confident that I understand the binary extractor and the frames_first/time_axis stuff.

**Comment by alejoe91** [comment]
frames_first should be time_axis=0. I can fix it tomorrow

**Comment by samuelgarcia** [comment]
Be carrelul, if you change theses kargs as it could break some code everywhere.
