### ISSUE TITLE
NwbExtractor fails as session and identifier are not set

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikeextractors#281]
In `write_recording` and `write_sorting`, `session_description` and `identifier` are set to `''`. However, this results in an Error when attempting to open the file with pynwb or when writing sorting data on a file created by `write_recording`.

Suggested fix: 
- add `session_description` and `identifier` as optional args in the write functions
- if None (by default) use `no description` and a random identifier.

@bendichter @luiztauffer does this sound reasonable?

**Comment by alejoe91** [comment]
Also this line: https://github.com/SpikeInterface/spikeextractors/blob/master/spikeextractors/extractors/nwbextractors/nwbextractors.py#L183

Should be:
spkt = sorting.get_unit_spike_train(unit_id=id) / fs

Making a PR now

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spikeextractors/pull/282

**Comment by seancav1967** [comment]
Please remove all bugs

**Comment by bendichter** [comment]
@alejoe91 yes, sounds great

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spikeextractors/pull/282
