### ISSUE TITLE
sorting.get_unit_spike_features() does not work as intended with frame ranges

### ISSUE THREAD

**Issue by luiztauffer** [SpikeInterface/spikeextractors#298]
I believe `sorting.get_unit_spike_features()` method is not working as intended when the user specifies a frame range.
I think the problem is in this line:
https://github.com/SpikeInterface/spikeextractors/blob/58fafe687ebb828fb465bc7240caf05bbd662d78/spikeextractors/sortingextractor.py#L157

Shouldn't only the indexes of spikes that fall within the defined range be used here instead of the frame range?

**Comment by colehurwitz** [comment]
Yes, I think you are right! This line doesn't make sense since it is trying to index the actual feature. I can fix this.

**Comment by alejoe91** [comment]
@luiztauffer thanks for spotting this and @colehurwitz for fixing :)

**Comment by colehurwitz** [comment]
Fixed! #300
