### ISSUE TITLE
request: Simple examples on Docs for loading custom data (i.e NumpyRecordingExtractor/NumpySortingExtractor)

### ISSUE THREAD

**Issue by sbtnRey** [SpikeInterface/spikeextractors#310]

**Comment by mhhennig** [comment]
How do you want to use this, what would be useful to show?

**Comment by sbtnRey** [comment]
Primarily how custom data should be formatted for the numpy extractor (i.e data structure format for channel values)

**Comment by alejoe91** [comment]
Hi @sbtnRey 

If I understand correctly, you have data loaded in memory (a numpy array) and you would like to create a NumpyRecordngExtractor object? 

In this case, you can check out [this tutorial](https://spikeinterface.readthedocs.io/en/latest/modules/extractors/plot_1_recording_extractor.html#sphx-glr-modules-extractors-plot-1-recording-extractor-py). You need to provide the timeseries and sampling frequency, and optionally the geometry. 

Is this what you need?

**Comment by sbtnRey** [comment]
Yeah, that was exactly what I needed. Thank you!
