### ISSUE TITLE
Openephys parallel 

### ISSUE THREAD

**Issue by benefron** [SpikeInterface/spikeextractors#318]
Hi,
Is there a way to run the extractor in parallel for each electrode file?
Ben

**Comment by alejoe91** [comment]
Hi Ben, 

Unfortunately no. I highly recommend saving in binary format instead if openephys so that the data are memmapped.

Cheers
Alessio

**Comment by benefron** [comment]
so change data I already have to binary? so it can run efficiently on HPC?

**Comment by alejoe91** [comment]
I don't think you can change the data you have to binary. But if you will acquire more data I recommend binary :)

**Comment by benefron** [comment]
what about this in the extractors:
write_to_binary_dat_format(self, save_path, time_axis=0, dtype=None, chunk_size=None):
     '''Saves the traces of this recording extractor into binary .dat format.

**Comment by alejoe91** [comment]
Hi @benefron unfortunately that won't work, because in order to write_to_binary you have to load the data into memory. Then you can save to binary and if you load it another time this will speed up things a lot

**Comment by benefron** [comment]
It might be good for me. I will save it to binary on my desktop and on the HPC run the binary file.
Thanks
