### ISSUE TITLE
Helper functions for exporting to different formats

### ISSUE THREAD

**Issue by colehurwitz** [SpikeInterface/spikeextractors#384]
@alejoe91 What do you think about having helper functions for all the exporting to different formats?  Something like: `export_to_format(format_name, **kwargs)` that calls the class methods we implemented already. I got a question about how to export to Neuroscope I think this could be a helpful change for new users.

**Comment by alejoe91** [comment]
Hi @colehurwitz 

I think that having the write_recording function is enough. We can point to that. The `export` notation is different than the `write` in our case, where `export` combines recording and sorting (as in phy). Let's focus on the new release and the docs before :)
