### ISSUE TITLE
AssertionError in KiloSortRecordingExtractor when channel_map is a subset (active channels only) of np.arange(n_channels_dat)

### ISSUE THREAD

**Issue by aliddell** [SpikeInterface/spikeextractors#387]
I don't know when (or if) the `channel_map` format changed from when [this dataset](http://data.cortexlab.net/singlePhase3/) was sorted, but I run into this assertion error when I try to load the dataset with a `KiloSortRecordingExtractor`:

```python
basedir = "/path/to/singlePhase3/data/"
ex = se.extractors.kilosortextractors.KiloSortRecordingExtractor(basedir)
```

gives me 

```ipython
c:\users\alanc\source\repos\spikeinterface\spikeextractors\spikeextractors\extractors\kilosortextractors\kilosortextractors.py in __init__(self, folder_path)
     12
     13     def __init__(self, folder_path):
---> 14         PhyRecordingExtractor.__init__(self, folder_path)
     15
     16

c:\users\alanc\source\repos\spikeinterface\spikeextractors\spikeextractors\extractors\phyextractors\phyextractors.py in __init__(self, folder_path)
     27         elif (phy_folder / 'channel_map.npy').is_file():
     28             channel_map = list(np.squeeze(np.load(phy_folder / 'channel_map.npy')))
---> 29             assert len(channel_map) == self.params['n_channels_dat']
     30         else:
     31             channel_map = list(range(self.params['n_channels_dat']))

AssertionError:
```

Looking at the code it's not clear to me how the recordings handle inactive channels.

**Comment by alejoe91** [comment]
Yep, the extractor assumes that there are no missing channels. Do you know how kilosort handle this? 

Maybe just removong that assertion and printing a warning message could work

**Comment by aliddell** [comment]
> Do you know how kilosort handle this?

If I had to guess, I'd say Kilosort probably does what JRCLUST does and ignores samples from those channels when processing.

I tried replacing the assert with a warn, ran into another assert:

```
~\source\repos\SpikeInterface\spikeextractors\spikeextractors\extractors\bindatrecordingextractor\bindatrecordingextractor.py in __init__(self, file_path, sampling_frequency, numchan, dtype, recording_channels, time_axis, geom, offset, gain, is_filtered)
     36         if recording_channels is not None:
     37             assert len(recording_channels) == self._timeseries.shape[0], \
---> 38                'Provided recording channels have the wrong length'
     39             self._channels = recording_channels
     40         else:

AssertionError: Provided recording channels have the wrong length
```

**Comment by alejoe91** [comment]
I see. So in that case we have to access the `self._timeseries` of the provided channels only

`self._timeseries[recording_channels]`

**Comment by aliddell** [comment]
That's right, that's how I would (and do) access them (`self._timeseries` is `nchannels x nsamples`, correct?).

**Comment by alejoe91** [comment]
Hi @aliddell 

Sorry for the delay here! Exactly the timeseries should have that shape (you can double check). 
Were you able to solve the issue? In that case, could you make a PR?

**Comment by MarineChap** [comment]
Hi all, 
We ran into the same problem in our lab. 
```
Traceback (most recent call last):
  File "/home/kasia/.config/spyder-py3/temp.py", line 11, in <module>
    recording = PhyRecordingExtractor('/media/kasia/K/Neuropixeldata/LS_K_7/120920/Neuropixel_data/Processed/catgt_120920-VR_g0')
  File "/home/kasia/miniconda3/envs/fklab/lib/python3.7/site-packages/spikeextractors/extractors/phyextractors/phyextractors.py", line 29, in __init__
    assert len(channel_map) == self.params['n_channels_dat']
```
There is only 260 channels in channel_map.npy while in params there is 384. 
Did you find a solution for this?

Thanks

**Comment by alejoe91** [comment]
Hi @MarineChap 

Yes! I was planning to make a PR by the end of the day actually (great timing :) )

Cheers
Alessio

**Comment by alejoe91** [comment]
@MarineChap @aliddell 

Can you try this PR: https://github.com/SpikeInterface/spikeextractors/pull/570 ?

**Comment by MarineChap** [comment]
Nice ! Testing it now
