### ISSUE TITLE
Add Spike2RecordingExtractor

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikeextractors#405]
@samuelgarcia would it be possible to ad Spike2 as a NEO extractor?

@deeptimittal12 would like to use SpikeInterface for their pipelines and some of the files are from Spike2

**Comment by samuelgarcia** [comment]
I can do it but for @deeptimittal12 it won't solve the problem as she need smrx file wheras smr file only are implemented.

**Comment by bendichter** [comment]
depends on https://github.com/NeuralEnsemble/python-neo/issues/424

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spikeextractors/pull/483
