### ISSUE TITLE
NeuroscopeSpikeExtractor

### ISSUE THREAD

**Issue by CodyCBakerPhD** [SpikeInterface/spikeextractors#411]
Hello, I was attempting to use the NeuroscopeSpikeExtractor function to retrieve spike times from .res and .clu files for use in the widgets and further processing. I noticed a repetitive error where one of the units, typically the last index, would be non-spiking (spike times array is empty) which causes issues with things as simple as plot_raster.

After digging into it, it seems the issue is with the NeuroscopeSpikeExtractor assuming that the cluster IDs start at 1 and go up to the number of units reported in the first line of the .clu file... However, the actual Neuroscope data suggests it is instead ordered from 0, ..., number of units - 1.

You can find a sample notebook illustrating the issue here: https://github.com/catalystneuro/buzsaki-lab-to-nwb/blob/refactor_v1.0.1/buzsaki_lab_to_nwb/original-code/Replicating_NeuroscopeSortingExtractor_Issue.ipynb

EDIT: It may be that cluster 0 is the identifier for unsorted spikes, implying that the number of sorted spiking clusters is the first line of the .clu file - 1?

EDIT 2: Confirmed that original cluster IDs of 0 are unsorted spikes (referred to as noise in the comments for the function), but also, original IDs of 1 are multi-unit spikes and so there are really n_clu - 2 many spiking clusters to extract starting from original ID 2 up to n_clu - 1. For a similar type of functionality, see https://github.com/catalystneuro/to_nwb/blob/9876a1baf4faf56ba54fe8ff7359129450e2aca0/to_nwb/neuroscope.py#L188-L216

**Comment by alejoe91** [comment]
HI @CodyCBakerPhD 

thanks for the report. Actually @alexmorley implemented the NeuroScopeExtractor.

We added now a new [base function](https://github.com/SpikeInterface/spikeextractors/blob/master/spikeextractors/sortingextractor.py#L703) for the SortingExtractor that can return unsorted spikes. This could return the cluster 0. 

For cluster 1, we could add an option`keep_mua_units` False by default, that would allow the user to include the mua clusters or not.

How does that sound? If you are getting familiar with the framework, would you like to make these changes in a PR? 

Cheers
Alessio

**Comment by CodyCBakerPhD** [comment]
That sounds like the best option, it should be a pretty easy change to make. Just to make sure I have the process correct, I should make a new branch, commit the changes there, and await comments/testing on your end until you merge it into the master?

**Comment by alejoe91** [comment]
You should fork the repo, make a new branch, make the changes, and then make a PR to spikeextractors/master from your fork :)

**Comment by alexmorley** [comment]
Happy to review. You are right I don't think I considered `0` units in my implementation because we don't use them.
