### ISSUE TITLE
How can I combine multiple recording variables?

### ISSUE THREAD

**Issue by pizzayamyam** [SpikeInterface/spikeextractors#434]
I export MDA files from rnd file with MATLAB. During this step, memory error often occurs. Therefore, I export this recording data into two different mda files. At this point, I have a problem in extracting recordings. I want to sort two files simultaneously. 
I tried to use 'run_sorters', however, there was some differences to set parameters between 'run_mountainsort4' and ' run_sorters'.
Please let me know how to merge recordings.
In addition, when I export_to_phy, this problem would also happen. 
Please let me know how to set 'recording= ' parameter.

**Comment by alejoe91** [comment]
Hi @pizzayamyam 

Sorry for the delay in replying to this! 

Are thw two files chunks of the same file? In that case you can concatenate them before running sorting as follows:

```
import spikeextractors as se
import spiketoolkit as st
import spikewidgets as sw

rec1 = se.MdaRecordingExtractor('path-to-folder1')
rec2 = se.MdaRecordingExtractor('path-to-folder2')

multirec = se.MultiRecordingTimeExtractor([rec1, rec2])

# now you can sort and export multirec to phy
multisort = ss.run_mountainsort4(multirec)

st.postprocessing.export_to_phy(multirec, multisort, 'phy-folder')
```

Let me know if this is what you were asking for!

Cheers
Alessio
