### ISSUE TITLE
SpikeGLXRecordingExtractor not working

### ISSUE THREAD

**Issue by zekearneodo** [SpikeInterface/spikeextractors#535]
Hi. Thanks for all this work, first of all.

I can instantiate a recording object if I use the pip package (pip install spikeextractors), but it blows up if I install it from the repo (forked master branch as of today 6AM PST).

The error I get:

`/mnt/cube/earneodo/repos/spikeextractors/spikeextractors/extractors/spikeglxrecordingextractor/spikeglxrecordingextractor.py in __init__(self, file_path, dtype)
     91 
     92         # set gains - convert from int16 to uVolt
---> 93         self.set_channel_gains(self._channels, gains*1e6)
     94         self._kwargs = {'file_path': str(Path(file_path).absolute()), 'dtype': dtype}
     95 

/mnt/cube/earneodo/repos/spikeextractors/spikeextractors/recordingextractor.py in set_channel_gains(self, gains, channel_ids)
    384                 for i in range(len(channel_ids)):
    385                     if isinstance(gains[i], (int, np.integer, float, np.float64)):
--> 386                         self.set_channel_property(channel_ids[i], 'gain', float(gains[i]))
    387                     else:
    388                         raise TypeError("all gains must be floats or ints")

/mnt/cube/earneodo/repos/spikeextractors/spikeextractors/recordingextractor.py in set_channel_property(self, channel_id, property_name, value)
    445                 raise ValueError(str(channel_id) + " is not a valid channel_id")
    446         else:
--> 447             raise TypeError(str(channel_id) + " must be an int")
    448 
    449     def get_channel_property(self, channel_id, property_name):

TypeError: 152.587890625 must be an int`

**Comment by alejoe91** [comment]
Thanks for the issue!! It was broken by a recent commit. Sorry about that, fixed it here: https://github.com/SpikeInterface/spikeextractors/pull/536

Can you test that it works on your side?

Cheers
Alessio
