### ISSUE TITLE
imec0.ap vs imec.ap

### ISSUE THREAD

**Issue by gmaggi** [SpikeInterface/spikeextractors#559]
Hi,

In a previous version of spikeextractors (0.9.0), it was possible to pass imec.ap.bin files. Now with 0.9.3, I get an error :
`spikeextractors/extractors/spikeglxrecordingextractor/spikeglxrecordingextractor.py", line 25, in __init__
    "'file_path' can be an imec0.ap, imec.lf, or nidq file"`
   
  Is it still possible to use imec.ap.bin  ?

Thanks!

**Comment by alejoe91** [comment]
@gmaggi this should fix it: https://github.com/SpikeInterface/spikeextractors/pull/560
