### ISSUE TITLE
Add remove_unit to NumpySortingExtractor

### ISSUE THREAD

**Issue by Dradeliomecus** [SpikeInterface/spikeextractors#580]
Hi,

Would it be possible to add a `remove_unit` to the `NumpySortingExtractor`? (something similar to the `exclude_unit` in the `PhySortingExtractor`).

Thanks!

**Comment by alejoe91** [comment]
I think that it would be better to use the CurationSortingExtractor in this case. Alternatively, you can first build all units and then add them all at once with the `set_times_labels` function

**Comment by Dradeliomecus** [comment]
Alright I'll use that.

Thank you!
