### ISSUE TITLE
AttributeError: 'AnalogSignal' object has no attribute 'gain'

### ISSUE THREAD

**Issue by crewl2** [SpikeInterface/spikeextractors#585]
I'm having an issue running spikeinterface. This is the line of code and the error I get. I'm running on Windows and have been able to install and run this successfully on another computer. Any insight? Thanks

trace_snippet = recording.get_traces(start_frame=int(fs*10), end_frame=int(fs*12))
print('Traces shape:', trace_snippet.shape)
w_ts = sw.plot_timeseries(recording)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-5bdd466ce2f8> in <module>
----> 1 trace_snippet = recording.get_traces(start_frame=int(fs*10), end_frame=int(fs*12))
      2 print('Traces shape:', trace_snippet.shape)
      3 w_ts = sw.plot_timeseries(recording)

~\anaconda3\lib\site-packages\spikeextractors\extraction_tools.py in corrected_args(*args, **kwargs)
    813 
    814         # pass recording as arg and rest as kwargs
--> 815         get_traces_correct_arg = func(args[0], **kwargs)
    816 
    817         return get_traces_correct_arg

~\anaconda3\lib\site-packages\spikeextractors\extractors\openephysextractors\openephysextractors.py in get_traces(self, channel_ids, start_frame, end_frame)
     45         elif self._dtype == 'float':
     46             return self._recording.analog_signals[0].signal[channel_ids, start_frame:end_frame] * \
---> 47                    self._recording.analog_signals[0].gain
     48 
     49     @check_get_ttl_args

AttributeError: 'AnalogSignal' object has no attribute 'gain'

**Comment by alejoe91** [comment]
Hi! We are on the prices of updating the package. This issue can be fixed by `pip install pyopenephys==1.0.7`
In a few days we'll release a new spikeinterface version that will be compatible with the latest pyopenephys version
