### ISSUE TITLE
[DOC] - Out of order argument descriptions

### ISSUE THREAD

**Issue by TomDonoghue** [SpikeInterface/spikeextractors#618]
I was exploring using SpikeInterface, and using some demos, and I noticed that some functions have the arguments described in the wrong order, which is a bit annoying for doing quick checks. For example `get_traces` and `get_snippets` in `spikeextractors/spikeextractors/recordingextractor.py` have this issue. 

If this is a mistake, I'm happy to do a quick sweep, and submit a PR to update this and any others I find. I just wanted to check first whether this is something to be fixed - I'm not yet super familiar with the module, and so it could be that there is some reason for these orderings that I am unfamiliar with.

**Comment by alejoe91** [comment]
Hi @TomDonoghue 

Thank you for spotting this! Sure if you have time, it would be awesome if you can make a PR to fix it :) it is definitely not intended
