### ISSUE TITLE
Sub and Multi Sorting Extractors need to copy over unit and spike properties

### ISSUE THREAD

**Issue by colehurwitz31** [SpikeInterface/spikeextractors#62]
As stated above, currently the unit and spike feature properties are not copied over from the original sorting extractors. We need to implement this

**Comment by alejoe91** [comment]
@colehurwitz31 I believe this is done with copyChannelProperties(). Right?

**Comment by colehurwitz31** [comment]
If it does this upon initialisation, then yes
