### ISSUE TITLE
file_path error

### ISSUE THREAD

**Issue by arthurz323** [SpikeInterface/spikeextractors#622]
As we are recording from multiple probes simultaneously,  we have both `imec0` and `imec1` in file names, and `imec1` is not listed in `spikeglxrecordingextractor.py`.

`AssertionError: 'file_path can be an imec.ap, imec.lf, imec0.ap, imec0.lf, or nidq file'`

**Comment by alejoe91** [comment]
Hi,

This is fixed in the latest version. Can you run `pip install --upgrade spikeextractors`?

**Comment by arthurz323** [comment]
Hi, yes we have upgraded it, and it's fine now, thanks!
