### ISSUE TITLE
MultiRecordingExtractor needs to copy over channel properties from original recording extractors

### ISSUE THREAD

**Issue by colehurwitz31** [SpikeInterface/spikeextractors#63]
As stated above, channel properties need to be copied over correctly to the multirecordingextractor.

**Comment by alejoe91** [comment]
@colehurwitz31 I believe this is done with copyChannelProperties(). Right?

**Comment by colehurwitz31** [comment]
Does it copy over all the passed in recording extractors properties upon initialisation? If so, then this issue can be closed
