### ISSUE TITLE
CED Sampling Frequency mismatch

### ISSUE THREAD

**Issue by luiztauffer** [SpikeInterface/spikeextractors#640]
Using sonpy `GetIdealRate()` function, we get a different rate from what the users set.
See https://github.com/catalystneuro/mease-lab-to-nwb/issues/36

We can get a good approximation of the set rate using other sonpy functions:
`rate = 1 / (f.GetTimeBase() * f.ChannelDivide(1))`
In the above case, this yields `rate=30030.030030030033`, which is not exactly 30.030, but better than 30.000
@samuelgarcia this might be relevant for you

**Comment by samuelgarcia** [comment]
In the original Spike2io in neo, I made the distinction between this ideal and the real rate.
In the CedIO I did not
But we could progagate this logic in CedIO easily with the same option.
In short the user choose bewteen ideal and real rate.

See this https://github.com/NeuralEnsemble/python-neo/blob/master/neo/rawio/spike2rawio.py#L200
