### ISSUE TITLE
load_probe_file generates recording child with incomplete properties

### ISSUE THREAD

**Issue by luiztauffer** [SpikeInterface/spikeextractors#652]
the function `se.load_probe_file()` returns a SubRecordingExtractor that seems to not be initialized with the same properties as the parent recording.
Check [this notebook](https://github.com/catalystneuro/mease-lab-to-nwb/blob/main/notebooks/CED_spikeinterface_pipeline.ipynb) for instance, cell 5. The resulting recording object does not have the correct gains and other properties.

**Comment by alejoe91** [comment]
@luiztauffer this is actually intended. the reason is that the gain is applied at each `get_traces` call, and if you have a `SubRecordingExtractor` the call is nested, so it would scale it twice...
