### ISSUE TITLE
Add `start_frames` to MultiExtractors

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikeextractors#77]
In the MultiRecording and MultiSorting extractor, we should add a `start_frames` argument in the constructors to account for pauses.

This could also affect data retreival and in particular filtering.

**Comment by colehurwitz31** [comment]
Are we sure that we want this? The issue with adding start_frames to MultiRecordingExtractors is that when it is passed to a spike sorter, then it will be a special case that the sorter has to deal with. If a MultiRecordingExtractor is a continuous recording, the sorter doesn't have to do anything different when analyzing a MultiRecordingExtractors.

We could have a function to sort by Epoch... maybe that could be a way to make sorters work with non-continuous MultiRecordingExtractors.

Thoughts, @samuelgarcia @alejoe91
