### ISSUE TITLE
dim for trace should be inverted.

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spikeextractors#81]
In actual implementation, when you do a **getTraces()** you have 2D array with (n_chan, n_sample).

This is the intuituive choice BUT for big files this lead to bad performences.

The reverse (n_sample, n_chan) in conetxt of long recording could lead to better performence.

A natural device give sample stream in the (n_sample, n_chan) order.
So many system using raw binary format go for (n_sample, n_chan) on thedisk . So a simple memmap can read the whole file.

Here with (n_chan, n_sample) a full memory copy  and translate must be done after the read.

Further, if you acces the signals by chunk in time, you need to acces bytes that are very distant inside the binary file.

I would highly, suggest to invert this and go for (n_chan, n_sample).

**Comment by colehurwitz31** [comment]
Hi Sam,

Inverting the dimensions does seem like a good idea if the performance would be affected otherwise.

Seeing as getTraces is a core function or our framework, I’m gonna give it some thought with the other people on the team about how and when to implement this.

**Comment by magland** [comment]
Hi Sam and Cole,
I am open to this possibility, but I want to point out that this could be an internal change (implementation) in how the data are stored internally for better performance -- without changing the API of recording extractors. Some formats will do it one way, and some will do it another -- the interface should be agnostic to that.
Jeremy

**Comment by colehurwitz31** [comment]
Hey Jeremy,

I am a bit confused about what you are suggesting. Are you saying that we can leave getTraces untouched, but change how data is stored when we extract it? 

Cole

**Comment by magland** [comment]
Yes. The point of an interface is that it abstracts away how data is handled internally. It seems against the philosophy of such a layer to modify it based on such implementation/efficiency optimization. IMO, it does not need to be changed in order to improve how data are stored.

**Comment by alejoe91** [comment]
@magland so how do we do it?

**Comment by magland** [comment]
There are various recording extractors. They are considered on a case-by-case basis. Which one should we focus on first -- for this issue?

**Comment by alejoe91** [comment]
I see, basically changing the specific extractors representation and returning the transpose should work

**Comment by magland** [comment]
Exactly. And numpy even has a way to specify the internal ordering of arrays. So you could either return a Fortran- or C-style ordering in the returned traces. For example, see: https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.asfortranarray.html

**Comment by magland** [comment]
So IMO, it's up to the individual extractors on how to do it efficiently. The interface is supposed to be able to  abstractly handle all kinds of formats and storage orders.

**Comment by colehurwitz31** [comment]
Sounds good. We can just focus on improving specific extractors then.

**Comment by samuelgarcia** [comment]
Of course with with numpy we can do a ```transpose()``` which internally change the array [strides](http://www.jessicayung.com/numpy-arrays-memory-and-strides/).

The thing is that numpy by default is C order and if by default the getTraces() render (n_chan, n_sample) then by default internally a traces will have continuous samples in memory for each channel.

So by default, unless an internal trick on strides (with transpose) is done every time, the performance will be affected when accessing data by chunk along the time axis (1).

I anderstand, that it is a pain to change this because it break many scripts but the project still is at its infancy...

But I don't want to be the guy whi insist.

It was long discussion inside neo team and my colleagues still think that the time should in dim1 (as here) but I really prefer dim0. Long debate...
