### ISSUE TITLE
BinDatRecordingExtractor should not rely on the fact the dtype is 'float32'

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spikeextractors#83]
Binary dataset are very often 'int16' or 'uint16'.

In BinDatRecordingExtractor the default dtype is 'float32'.

The dtype should be mandatory in any case without default value. It can lead to many deep and hard-to-errors, trust me.

Less important:
  * ```dtype == None``` should be ```dtype is None```
  * ```dtype=np.float32``` should be in the signature rather than in **if** because it is more explicit.

**Comment by colehurwitz31** [comment]
I think that is a great point. I agree that we should make the dtype mandatory. I will fix that.

**Comment by colehurwitz31** [comment]
Fixed
