### ISSUE TITLE
add getChannelLocations() and getChannelGroups() in RecordingExtractor

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikeextractors#97]
maybe also setters?

**Comment by alejoe91** [comment]
also setChannelLocations() setChannelGroups()

**Comment by colehurwitz31** [comment]
Should we have getChannelLocations() or should we have getChannelLocation() (multiple vs. single locations)

**Comment by alejoe91** [comment]
5b3d1fd10214cb6b197f10a6641551bf8988b07c
